name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${070ee94e-23a6-4618-91e8-2f5d2c9140c5}
      - uses: actions/setup-node@master
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: make setup
      - name: run lint
        run: make lint
      - name: run tests
        run: make test
