name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${1f283a04-6eb7-4e8a-8348-07293e0a6705}
      - uses: actions/setup-node@master
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: make setup
      - name: run lint
        run: make lint
      - name: run tests
        run: make test
